Feature - Add extension to support max apk size
vanniktech/gradle-android-apk-size-plugin pull request #49
Opened 2017-03-06 06:13 UTC by jaredsburrows

@vanniktech Solves #48 

Add extension to support max apk size

2017-03-06 06:59 UTC, jaredsburrows commented on README.md
> +    maxApkSize = 5800000
Add appropriate documentation.

2017-03-06 06:59 UTC, jaredsburrows commented on src/main/groovy/com/vanniktech/android/apk/size/ApkSizeTask.groovy
> +        failBuildMaxMethods(apkSize, extension.maxApkSize)
Run this method last, so the user(developer) can see the exception after the reports have printed to STDOUT and saved to disk.

2017-03-06 11:05 UTC, vanniktech reviewed
Any reason for changing all the quotes as well as the parenthesis?

2017-03-06 14:47 UTC, jaredsburrows commented
It was mixed in some areas, I was just trying to make it consistent.

On Mar 6, 2017 3:05 AM, "Niklas Baudy" <notifications@github.com> wrote:

> *@vanniktech* commented on this pull request.
>
> Any reason for changing all the quotes as well as the parenthesis?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vanniktech/gradle-android-apk-size-plugin/pull/49#pullrequestreview-25223749>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABqMSBHoKZjL4RIuQl5w8Rlq5NZ4Vttcks5ri-h1gaJpZM4MTwvC>
> .
>

2017-03-06 21:45 UTC, jaredsburrows commented on src/test/groovy/com/vanniktech/android/apk/size/ApkSizeTaskSpec.groovy
> +        task.extension = new ApkSizeExtension(maxApkSize: 500)
Add fake size for test.

2017-03-07 04:08 UTC, jaredsburrows commented
@vanniktech Let me know what you think.

2017-03-07 08:49 UTC, vanniktech requested changes

2017-03-07 08:49 UTC, vanniktech commented on README.md
> +- `maxApkSize`: Set the max APK size. Greater than specified size will fail the build. Default is -1.
should say in which unit the size is

2017-03-07 08:49 UTC, vanniktech commented on src/main/groovy/com/vanniktech/android/apk/size/ApkSizeExtension.groovy
> +   * Set the max APK size. Greater than specified size will fail the build.
should say in which unit the size is

2017-03-07 08:49 UTC, vanniktech commented on src/main/groovy/com/vanniktech/android/apk/size/ApkSizeTask.groovy
> +    ApkSizeExtension extension
nit: newline between

2017-03-07 08:49 UTC, vanniktech commented on src/main/groovy/com/vanniktech/android/apk/size/ApkSizeTask.groovy
> +        failBuildMaxMethods(apkSize, extension.maxApkSize)
👍

2017-03-07 08:49 UTC, vanniktech commented on src/main/groovy/com/vanniktech/android/apk/size/ApkSizeTask.groovy
> +     * Fails the build when a user specifies a "max apk size" for their current build.
not needed

2017-03-07 08:49 UTC, vanniktech commented on src/main/groovy/com/vanniktech/android/apk/size/ApkSizeTask.groovy
> +            throw new GradleException(String.format("The current APK is %d, the current max is: %d.", apkSize, maxApkSize))
also here add the units

2017-03-07 08:49 UTC, vanniktech commented on src/test/groovy/com/vanniktech/android/apk/size/ApkSizeTaskSpec.groovy
> +        task.extension = new ApkSizeExtension(maxApkSize: 500)
It does not throw though, right?

2017-03-07 16:31 UTC, jaredsburrows commented on src/main/groovy/com/vanniktech/android/apk/size/ApkSizeTask.groovy
> +     * Fails the build when a user specifies a "max apk size" for their current build.
You do not want comments?

2017-03-07 16:31 UTC, jaredsburrows commented on src/main/groovy/com/vanniktech/android/apk/size/ApkSizeTask.groovy
> +            throw new GradleException(String.format("The current APK is %d, the current max is: %d.", apkSize, maxApkSize))
kb. ok.

2017-03-07 16:31 UTC, jaredsburrows commented on src/test/groovy/com/vanniktech/android/apk/size/ApkSizeTaskSpec.groovy
> +        task.extension = new ApkSizeExtension(maxApkSize: 500)
No but `extension` needs to be initiated.

2017-03-07 16:32 UTC, jaredsburrows commented on src/main/groovy/com/vanniktech/android/apk/size/ApkSizeTask.groovy
> +    ApkSizeExtension extension
There weren't new lines between the others.

2017-03-07 16:32 UTC, jaredsburrows commented on src/main/groovy/com/vanniktech/android/apk/size/ApkSizeExtension.groovy
> +   * Set the max APK size. Greater than specified size will fail the build.
kb. ok.

2017-03-07 16:32 UTC, jaredsburrows commented on README.md
> +- `maxApkSize`: Set the max APK size. Greater than specified size will fail the build. Default is -1.
kb. ok.

2017-03-07 16:33 UTC, vanniktech commented on src/main/groovy/com/vanniktech/android/apk/size/ApkSizeTask.groovy
> +     * Fails the build when a user specifies a "max apk size" for their current build.
The method name is enough in this case. No need to add those extra comments.

2017-03-14 14:51 UTC, jaredsburrows commented
@vanniktech Any other changes?

2017-03-22 13:11 UTC, vanniktech approved these changes
Cool thanks. Sorry that it took forever 👍

2017-03-22 13:11 UTC, merged

2017-03-22 22:27 UTC, jaredsburrows commented
@vanniktech Np. I need to write a few tests for it as well!